export const baseSections = [
  { section: "A1", score: 86 },
  { section: "A2", score: 78 },
  { section: "A3", score: 55 },
  { section: "A4", score: 69 },
  { section: "A5", score: 74 },
  { section: "A6", score: 94 },
  { section: "A7", score: 55 },
  { section: "A11", score: 78 },
  { section: "A12", score: 55 },
  { section: "A13", score: 78 },
  { section: "A14", score: 55 },
  { section: "A15", score: 82 },
  { section: "A16", score: 74 },
  { section: "A17", score: 78 },
  { section: "A19", score: 78 },
  { section: "J1", score: 78 },
  { section: "J2", score: 55 },
  { section: "J3", score: 55 },
  { section: "J4", score: 55 },
  { section: "J5", score: 50 },
  { section: "O1", score: 78 },
  { section: "O2", score: 50 },
  { section: "O3", score: 63 },
  { section: "O4", score: 50 },
  { section: "O5", score: 50 },
  { section: "M1", score: 74 },
  { section: "M2", score: 50 },
  { section: "R1", score: 90 },
  { section: "R2", score: 82 },
  { section: "R3", score: 50 },
  { section: "S1", score: 50 },
  { section: "BBA A", score: 69 },
  { section: "BBA B", score: 50 },
];