export const baseSections = [
  { section: "A1", score: 140 },
  { section: "A2", score: 100 },
  { section: "A3", score: 0 },
  { section: "A4", score: 40 },
  { section: "A5", score: 70 },
  { section: "A6", score: 200 },
  { section: "A7", score: 0 },
  { section: "A8", score: 0 },
  { section: "A9", score: 0 },
  { section: "A10", score: 0 },
  { section: "A11", score: 100 },
  { section: "A12", score: 0 },
  { section: "A13", score: 100 },
  { section: "A14", score: 0 },
  { section: "A15", score: 75 },
  { section: "A16", score: 70 },
  { section: "A17", score: 95 },
  { section: "A18", score: 0 },
  { section: "A19", score: 95 },
  { section: "J1", score: 80 },
  { section: "O1", score: 100 },
  { section: "O2", score: 0 },
  { section: "O3", score: 25 },
  { section: "O4", score: 0 },
  { section: "O5", score: 0 },
  { section: "M1", score: 70 },
  { section: "M2", score: 0 },
  { section: "R1", score: 165 },
  { section: "R2", score: 105 },
  { section: "R3", score: 0 },
  { section: "S1", score: 0 },
  { section: "BBA A", score: 40 },
  { section: "BBA B", score: 0 },
  { section: "BCA", score: 0 },
];
